version: "3"
services:
  dev:
    build: .
    image: hub.gaoshiwang.cn/hotel_api:latest
    command: python manage.py runserver 0.0.0.0:7070
    volumes:
      - .:/code
      - ./docker_local:/data
    ports:
      - "7070:7070"
    environment:
      - PYTHONPATH=/code
      - HOTEL_API_SETTINGS=main.config.dev
    network_mode: bridge
  pro:
    image: hub.gaoshiwang.cn/hotel_api:latest
    command: supervisord -c /code/deploy/supervisord.conf
    volumes:
      - .:/code
      - /data/report_api:/data
    ports:
      - "8010:8010"
      - "9101:9001"
    environment:
      - PYTHONPATH=/code
      - HOTEL_API_SETTINGS=main.config.product
      - COLLECTD_DOCKER_APP=manual_data_container
    network_mode: bridge
    sysctls:
      net.core.somaxconn: 16384
    restart: always