version: "3"
services:
  dev:
    build: .
    image: hub.gaoshiwang.cn/hotel_api:latest
    command: python manage.py runserver 0.0.0.0:7070
    volumes:
      - .:/code
      - ./docker_local:/data
    ports:
      - "7070:7070"
    environment:
      - PYTHONPATH=/code
      - HOTEL_API_SETTINGS=main.config.local
    network_mode: bridge
    external_links:
      - product_redis:redis
      - product_mysql:mysql
  pro:
    image: hub.gaoshiwang.cn/hotel_api:latest
    command: supervisord -c /code/deploy/supervisord.conf
    volumes:
      - .:/code
      - /data/hotel_api:/data
    ports:
      - "8010:8010"
      - "9101:9001"
    environment:
      - PYTHONPATH=/code
      - HOTEL_API_SETTINGS=main.config.product
    network_mode: bridge
    sysctls:
      net.core.somaxconn: 16384
    restart: always
    external_links:
      - redis:redis
      - mysql:mysql

  celery_test:
    image: hub.gaoshiwang.cn/hotel_api:latest
    command: supervisord -c /code/deploy/celery_supervisord.conf
    volumes:
      - .:/code
      - ./docker_local:/data
    environment:
      - PYTHONPATH=/code
      - HOTEL_API_SETTINGS=main.config.local
    network_mode: bridge
    sysctls:
      net.core.somaxconn: 16384
    restart: always
    external_links:
      - redis:redis
  celery_pro:
    image: hub.gaoshiwang.cn/hotel_api:latest
    command: supervisord -c /code/deploy/celery_supervisord.conf
    volumes:
      - .:/code
      - /data/hotel_api:/data
    environment:
      - PYTHONPATH=/code
      - HOTEL_API_SETTINGS=main.config.product
    network_mode: bridge
    sysctls:
      net.core.somaxconn: 16384
    restart: always
    external_links:
      - redis:redis
      - mysql:mysql
