# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-20 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.modelfields.CompressionImageField
import main.modelfields.JsonFields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRefundedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_address', models.CharField(blank=True, default='', max_length=200, verbose_name='\u9000\u6b3e\u6536\u8d27\u5730\u5740')),
                ('refunded_name', models.CharField(blank=True, default='', max_length=200, verbose_name='\u9000\u6b3e\u6536\u8d27\u4eba')),
                ('refunded_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='\u9000\u6b3e\u8054\u7cfb\u7535\u8bdd')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u90ae\u5bc4\u4fe1\u606f',
                'verbose_name_plural': '\u90ae\u5bc4\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('banner_images', models.CharField(help_text='\u5b58\u50a8\u7edd\u5bf9\u8def\u5f84', max_length=300, verbose_name='\u6a2a\u5e45\u56fe\u7247')),
                ('jump_url', models.CharField(blank=True, help_text='\u5b58\u50a8\u7edd\u5bf9\u8def\u5f84', max_length=300, null=True, verbose_name='\u8df3\u8f6c\u8fde\u63a5')),
                ('is_show', models.BooleanField(default=False, help_text='\u662f\u5426\u53ef\u7528\u5728\u524d\u7aef\u5c55\u793a', verbose_name='\u662f\u5426\u5c55\u793a')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.PositiveIntegerField(default=0, verbose_name='\u5546\u54c1\u6570\u91cf')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='\u56de\u590d\u65f6\u95f4')),
                ('reply_content', models.CharField(max_length=200, verbose_name='\u56de\u590d\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u56de\u590d',
                'verbose_name_plural': '\u8bc4\u8bba\u56de\u590d',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5fae\u4fe1openid')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5fae\u4fe1\u56de\u8bddkey')),
                ('phone', models.CharField(blank='', default='', max_length=15, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('user_name', models.CharField(default='', max_length=30, verbose_name='\u7528\u6237\u59d3\u540d')),
                ('avatar_url', models.CharField(default='', max_length=100, verbose_name='\u5934\u50cf\u94fe\u63a5')),
                ('sex', models.IntegerField(choices=[(10, '\u672a\u77e5'), (20, '\u7537'), (30, '\u5973')], default=10, verbose_name='\u6027\u522b')),
                ('contact_addr', models.CharField(blank='', default='', max_length=100, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('is_distribution', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5206\u9500\u4eba\u5458')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='\u5206\u9500\u5956\u91d1')),
                ('recharge_balance', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='\u5145\u503c\u4f59\u989d', max_digits=10, verbose_name='\u4f59\u989d')),
                ('free_balance', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='\u5145\u503c\u8d60\u9001\u91d1\u989d', max_digits=10, verbose_name='\u5956\u52b1\u91d1')),
                ('sell_user', models.ForeignKey(blank=True, help_text='\u63a8\u9500\u4eba', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u5ba2\u6237\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ConsumerBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.IntegerField(choices=[(10, '\u589e\u52a0'), (20, '\u6d88\u8d39')], default=10, verbose_name='\u4f59\u989d\u7c7b\u578b')),
                ('message', models.CharField(default=0, max_length=30, verbose_name='\u6d88\u8d39\u5907\u6ce8')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='\u6b63\u6570\u4ee3\u8868\u4e3a\u5145\u503c\u3002\u8d1f\u6570\u4ee3\u8868\u6d88\u8d39', max_digits=10, verbose_name='\u6d88\u8d39\u91d1\u989d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6d88\u8d39\u65f6\u95f4')),
                ('left_balance', models.DecimalField(decimal_places=2, default=0, help_text='\u7528\u6237\u5269\u4f59\u4f59\u989d', max_digits=10, verbose_name='\u5269\u4f59\u4f59\u989d')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u5bf9\u5e94\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4f59\u989d\u8be6\u60c5',
                'verbose_name_plural': '\u7528\u6237\u4f59\u989d\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='DistributionApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_status', models.IntegerField(choices=[(10, '\u63d0\u4ea4\u6210\u529f'), (20, '\u62d2\u7edd'), (30, '\u5b8c\u6210'), (40, '\u64a4\u56de\u7533\u8bf7')], default=10, verbose_name='\u7533\u8bf7\u72b6\u6001')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('apply_remark', models.CharField(max_length=520, verbose_name='\u7533\u8bf7\u539f\u56e0')),
                ('success_time', models.DateTimeField(blank=True, null=True, verbose_name='\u6210\u529f\u65f6\u95f4')),
                ('operator_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('is_success', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7533\u8bf7\u6210\u529f')),
                ('fail_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='\u5931\u8d25\u539f\u56e0')),
                ('consumer', models.ForeignKey(blank=True, help_text='\u7528\u6237', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer')),
            ],
            options={
                'verbose_name': '\u5206\u9500\u7533\u8bf7\u8bb0\u5f55',
                'verbose_name_plural': '\u5206\u9500\u7533\u8bf7\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='DistributionBonusDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(10, '\u672a\u77e5'), (20, '\u6210\u529f'), (30, '\u5931\u8d25'), (40, '\u53d6\u6d88')], default=10, verbose_name='\u72b6\u6001')),
                ('detail_type', models.IntegerField(default=0, help_text='\u5956\u91d1\u660e\u7ec6\u7c7b\u578b', verbose_name='\u7c7b\u578b')),
                ('last_bonus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5269\u4f59\u5956\u91d1')),
                ('use_bonus', models.DecimalField(decimal_places=2, help_text='\u6d88\u8d39\u91d1\u989d', max_digits=10, verbose_name='\u4f7f\u7528\u91d1\u989d')),
                ('remark', models.CharField(max_length=100, verbose_name='\u4f7f\u7528\u539f\u56e0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('operator_time', models.DateTimeField(auto_now=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_bonus_detail', to='main.Consumer')),
            ],
            options={
                'verbose_name': '\u5206\u9500\u5956\u91d1\u660e\u7ec6',
                'verbose_name_plural': '\u5206\u9500\u5956\u91d1\u660e\u7ec6',
            },
        ),
        migrations.CreateModel(
            name='DistributionBonusPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_order', models.CharField(blank=True, db_index=True, error_messages={'unique': '\u8ba2\u5355\u53f7\u9519\u8bef'}, max_length=20, null=True, verbose_name='\u63d0\u53d6\u8ba2\u5355\u53f7')),
                ('pick_status', models.IntegerField(blank=True, choices=[(10, '\u63d0\u4ea4\u7533\u8bf7'), (20, '\u6b63\u5728\u5904\u7406'), (30, '\u8f6c\u8d26\u4e2d'), (40, '\u5b8c\u6210'), (50, '\u63d0\u53d6\u5931\u8d25'), (60, '\u53d6\u6d88\u7533\u8bf7')], default=10, verbose_name='\u63d0\u53d6\u72b6\u6001')),
                ('pick_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u63d0\u53d6\u91d1\u989d')),
                ('pick_time', models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('success_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('transfer_time', models.DateTimeField(blank=True, null=True, verbose_name='\u8f6c\u8d26\u65f6\u95f4')),
                ('fail_remark', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='\u5931\u8d25\u539f\u56e0')),
                ('operator_time', models.DateTimeField(auto_now=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer')),
            ],
            options={
                'verbose_name': '\u63d0\u53d6\u5206\u9500\u91d1\u989d\u7533\u8bf7',
                'verbose_name_plural': '\u63d0\u53d6\u5206\u9500\u91d1\u989d\u7533\u8bf7',
            },
        ),
        migrations.CreateModel(
            name='DistributionWXInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_payment_no', models.CharField(blank=True, default='', help_text='\u5fae\u4fe1\u5185\u90e8\u8ba2\u5355\u53f7', max_length=100, verbose_name='\u5fae\u4fe1\u4ed8\u6b3e\u8ba2\u5355\u53f7')),
                ('distribution_order_id', models.CharField(blank=True, default='', help_text='\u6210\u529f\u63d0\u53d6\u65f6\u7684\u8ba2\u5355\u53f7', max_length=40, verbose_name='\u63d0\u53d6\u8f6c\u8d26\u8ba2\u5355\u53f7')),
                ('wx_result_code', models.CharField(blank=True, default='', max_length=20, verbose_name='\u5fae\u4fe1\u4e1a\u52a1\u7ed3\u679c')),
                ('err_code', models.CharField(blank=True, default='', max_length=30, verbose_name='\u5fae\u4fe1\u9519\u8bef\u4ee3\u7801')),
                ('err_code_des', models.CharField(blank=True, default='', max_length=100, verbose_name='\u5fae\u4fe1\u9519\u8bef\u63cf\u8ff0')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5fae\u4fe1\u5230\u8d26\u65f6\u95f4')),
                ('distribution_pick', models.ForeignKey(help_text='\u4e00\u4e2a\u7533\u8bf7\u53ef\u80fd\u6709\u591a\u4e2a\u8f6c\u8d26', on_delete=django.db.models.deletion.CASCADE, to='main.DistributionBonusPick')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('goods_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('is_integral', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u79ef\u5206\u5151\u6362')),
                ('is_promotion', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4fc3\u9500')),
                ('is_special', models.BooleanField(default=False, help_text='\u662f\u5426\u4e3a\u4f1a\u5458, \u5f53\u6b64\u4e3aTrue\u65f6\uff0c\u9700\u8981\u4f20\u9012\u4f1a\u5458\u6743\u76ca', verbose_name='\u662f\u5426\u4e3a\u4f1a\u5458')),
                ('need_integral', models.PositiveIntegerField(blank=True, default=0, verbose_name='\u6240\u9700\u79ef\u5206')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e0a\u67b6')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('cover_image', models.CharField(default='', max_length=100, verbose_name='\u5c01\u9762\u56fe')),
                ('images', main.modelfields.JsonFields.JSONField(blank=True, default=[], null=True, verbose_name='\u6240\u6709\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_active', models.BooleanField(default=False, help_text='\u9ed8\u8ba4\u4e0d\u4e0a\u67b6', verbose_name='\u662f\u5426\u4e0a\u67b6')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u5206\u7c7b',
                'verbose_name_plural': '\u5546\u54c1\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='GrowthValueSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_growth_value', models.PositiveIntegerField(default=0, verbose_name='\u6700\u5c0f\u6210\u957f\u503c')),
                ('max_growth_value', models.PositiveIntegerField(default=2147483648, help_text='2147483647', verbose_name='\u6700\u5927\u6210\u957f\u503c')),
                ('level', models.CharField(help_text='\u6210\u957f\u503c\u5bf9\u5e94\u7b49\u7ea7', max_length=10, verbose_name='\u7b49\u7ea7')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6210\u957f\u503c\u5bf9\u5e94\u7b49\u7ea7',
                'verbose_name_plural': '\u6210\u957f\u503c\u5bf9\u5e94\u7b49\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='\u5bbe\u9986\u540d\u79f0')),
                ('province', models.CharField(default='\u56db\u5ddd\u7701', max_length=100, verbose_name='\u7701\u4efd')),
                ('city', models.CharField(default='\u6210\u90fd\u5e02', max_length=20, verbose_name='\u5e02')),
                ('area', models.CharField(default='', max_length=100, verbose_name='\u533a')),
                ('street', models.CharField(default='', max_length=200, verbose_name='\u8857\u9053\u5730\u5740')),
                ('longitude', models.CharField(default='', max_length=100, verbose_name='\u7ecf\u5ea6')),
                ('latitude', models.CharField(default='', max_length=100, verbose_name='\u7eac\u5ea6')),
                ('images', main.modelfields.JsonFields.JSONField(blank=True, default='[]', help_text='\u56fe\u7247\uff0c\u5b58\u653e\u56fe\u7247\u7684URL', null=True, verbose_name='\u56fe\u7247')),
                ('hotel_profile', models.TextField(verbose_name='\u5bbe\u9986\u7b80\u4ecb')),
                ('cover_images', models.CharField(default='', max_length=100, verbose_name='\u5c01\u9762\u56fe')),
                ('tel', models.CharField(default='', max_length=50, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('tags', main.modelfields.JsonFields.JSONField(blank=True, default=[], help_text='\u6807\u7b7e,\u5b58\u653e\u4e3a\u6570\u7ec4,\u6570\u636e\u5e93\u4e3ajson\u540e\u7684list', verbose_name='\u6807\u7b7e\u7ba1\u7406')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5bf9\u5916\u5f00\u653e')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5bbe\u9986\u4fe1\u606f',
                'verbose_name_plural': '\u5bbe\u9986\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='HotelOrderComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_show', models.IntegerField(choices=[(10, '\u8bc4\u8bba\u4eba\u53ef\u89c1'), (20, '\u5ba1\u6838\u901a\u8fc7')], default=10, help_text='\u9ed8\u8ba4\u53ea\u80fd\u591f\u8bc4\u8bba\u4eba\u53ef\u89c1', verbose_name='\u8bc4\u8bba\u53ef\u89c1')),
                ('content', models.CharField(default='', max_length=200, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('comment_level', models.IntegerField(choices=[(1, '\u4e00\u5206'), (2, '\u4e24\u5206'), (3, '\u4e09\u5206'), (4, '\u56db\u5206'), (5, '\u4e94\u5206')], default=5, verbose_name='\u8bc4\u8bba\u7b49\u7ea7')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('no_show_reason', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='\u4e0d\u663e\u793a\u539f\u56e0')),
                ('is_reply', models.BooleanField(default=False, verbose_name='\u662f\u5426\u56de\u590d')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u8bc4\u8bba',
                'verbose_name_plural': '\u8ba2\u5355\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='HotelOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_nums', models.PositiveIntegerField(default=0, verbose_name='\u623f\u95f4\u6570\u91cf')),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5165\u4f4f\u65f6\u623f\u95f4\u5355\u4ef7')),
                ('reserve_check_in_time', models.DateTimeField(help_text='\u7528\u6237\u9884\u5b9a\u65f6\u95f4\uff0c12\u70b9\u4ee5\u540e', null=True, verbose_name='\u9884\u5b9a\u5165\u4f4f\u65f6\u95f4')),
                ('reserve_check_out_time', models.DateTimeField(help_text='\u7528\u6237\u9884\u5b9a\u65f6\u95f4', null=True, verbose_name='\u9884\u5b9a\u9000\u623f\u65f6\u95f4')),
                ('contact_name', models.CharField(default='', max_length=50, verbose_name='\u8054\u7cfb\u4eba')),
                ('contact_phone', models.CharField(default='', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
            ],
            options={
                'verbose_name': '\u4f4f\u5bbf\u8ba2\u5355\u8be6\u60c5',
                'verbose_name_plural': '\u4f4f\u5bbf\u8ba2\u5355\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', main.modelfields.CompressionImageField.CompressionImageField(upload_to=b'')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u56fe\u7247',
                'verbose_name_plural': '\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='IntegralDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral', models.IntegerField(default=0, verbose_name='\u79ef\u5206\u60c5\u51b5')),
                ('integral_type', models.IntegerField(choices=[(10, '\u589e\u52a0'), (20, '\u6d88\u8d39')], default=10, verbose_name='\u79ef\u5206\u7c7b\u578b')),
                ('remark', models.CharField(blank=True, default='', help_text='\u672c\u6b21\u79ef\u5206\u6765\u6e90', max_length=100, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u6d88\u8d39\u65f6\u95f4', verbose_name='\u6d88\u8d39\u65f6\u95f4')),
                ('left_integral', models.IntegerField(default=0, verbose_name='\u5269\u4f59\u79ef\u5206')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u79ef\u5206\u660e\u7ec6',
                'verbose_name_plural': '\u79ef\u5206\u660e\u7ec6',
            },
        ),
        migrations.CreateModel(
            name='IntegralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral', models.PositiveIntegerField(default=0, help_text='\u79ef\u5206\u53ef\u4ee5\u7528\u4e8e\u5151\u6362\u7269\u54c1', verbose_name='\u603b\u79ef\u5206')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('growth_value', models.PositiveIntegerField(default=0, help_text='\u6210\u957f\u503c\u7b49\u4e8e\u6240\u6709\u79ef\u5206', verbose_name='\u6210\u957f\u503c')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integral_info', to='main.Consumer', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u79ef\u5206',
                'verbose_name_plural': '\u7528\u6237\u79ef\u5206',
            },
        ),
        migrations.CreateModel(
            name='IntegralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral', models.PositiveIntegerField(verbose_name='\u79ef\u5206')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u94b1')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u79ef\u5206\u914d\u7f6e',
                'verbose_name_plural': '\u79ef\u5206\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='MarketOrderContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee_name', models.CharField(default='', max_length=50, verbose_name='\u6536\u8d27\u4eba\u59d3\u540d')),
                ('consignee_address', models.CharField(default='', max_length=200, verbose_name='\u6536\u8d27\u5730\u5740')),
                ('consignee_phone', models.CharField(default='', max_length=15, verbose_name='\u6536\u8d27\u4eba\u7535\u8bdd')),
            ],
            options={
                'verbose_name': '\u5546\u573a\u8ba2\u5355\u6536\u8d27\u4eba',
                'verbose_name_plural': '\u5546\u573a\u8ba2\u5355\u6536\u8d27\u4eba',
            },
        ),
        migrations.CreateModel(
            name='MarketOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='\u9500\u552e\u5355\u4ef7')),
                ('goods_integral', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='\u5151\u6362\u79ef\u5206\u5355\u4ef7')),
                ('nums', models.PositiveIntegerField(default=0, verbose_name='\u8d2d\u4e70\u6570\u91cf')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Goods')),
            ],
            options={
                'verbose_name': '\u5546\u573a\u8ba2\u5355\u660e\u7ec6',
                'verbose_name_plural': '\u5546\u573a\u8ba2\u5355\u660e\u7ec6',
            },
        ),
        migrations.CreateModel(
            name='MarketOrderExpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_id', models.CharField(max_length=100, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('express_name', models.CharField(max_length=100, verbose_name='\u5feb\u9012\u540d\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u5feb\u9012\u4fe1\u606f',
                'verbose_name_plural': '\u8ba2\u5355\u5feb\u9012\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='\u63d0\u9192\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_active', models.BooleanField(default=True, help_text='\u662f\u5426\u6709\u6548,\u9ed8\u8ba4\u4e3a\u6709\u6548', verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'verbose_name': '\u7ad9\u5185\u63d0\u9192',
                'verbose_name_plural': '\u7ad9\u5185\u63d0\u9192',
            },
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='\u610f\u89c1\u5185\u5bb9')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Consumer')),
            ],
            options={
                'verbose_name': '\u610f\u89c1',
                'verbose_name_plural': '\u610f\u89c1',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField(choices=[(10, '\u5546\u573a\u8ba2\u5355'), (20, '\u4f4f\u5bbf\u8ba2\u5355')], db_index=True, verbose_name='\u8ba2\u5355\u7c7b\u578b')),
                ('order_id', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='\u8ba2\u5355\u53f7')),
                ('order_status', models.IntegerField(blank=True, choices=[(10, '\u672a\u652f\u4ed8'), (15, '\u5f85\u53d1\u8d27'), (20, '\u5f85\u6536\u8d27'), (25, '\u5f85\u5165\u4f4f'), (30, '\u5165\u4f4f\u4e2d'), (35, '\u5f85\u8bc4\u4ef7'), (45, '\u5df2\u53d6\u6d88'), (40, '\u5df2\u8bc4\u4ef7'), (46, '\u7533\u8bf7\u9000\u6b3e'), (48, '\u8bf7\u9000\u8d27'), (50, '\u7b49\u5f85\u9000\u6b3e'), (55, '\u9000\u6b3e\u4e2d'), (60, '\u9000\u6b3e\u5b8c\u6210'), (61, '\u9000\u6b3e\u62d2\u7edd'), (65, '\u5df2\u8fc7\u671f'), (70, '\u5df2\u5220\u9664')], db_index=True, default=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_type', models.IntegerField(choices=[(10, '\u79ef\u5206'), (20, '\u4f59\u989d'), (30, '\u5fae\u4fe1\u652f\u4ed8')], db_index=True, default=30, help_text='\u9ed8\u8ba4\u5fae\u4fe1\u652f\u4ed8', verbose_name='\u652f\u4ed8\u65b9\u5f0f')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('num', models.PositiveIntegerField(default=0, help_text='\u5546\u54c1\u603b\u6570\u6216\u8005\u623f\u95f4\u603b\u6570', verbose_name='\u603b\u6570')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, help_text='\u9700\u8981\u652f\u4ed8\u7684\u91d1\u989d', max_digits=10, verbose_name='\u8ba2\u5355\u4ef7\u683c')),
                ('integral', models.PositiveIntegerField(blank=True, default=0, help_text='\u53ea\u6709\u5f53\u652f\u4ed8\u65b9\u5f0f\u4e3a\u79ef\u5206\u65f6\u624d\u4f1a\u6709\u8fd9\u4e2a\u5b57\u6bb5', null=True, verbose_name='\u79ef\u5206\u603b\u989d')),
                ('operator_time', models.DateTimeField(blank=True, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('refund_reason', models.CharField(blank=True, default='', help_text='\u9000\u6b3e\u65f6,\u5fc5\u987b\u586b\u5199', max_length=200, verbose_name='\u9000\u6b3e\u539f\u56e0')),
                ('user_remark', models.TextField(blank=True, default='', verbose_name='\u7528\u6237\u5907\u6ce8')),
                ('operator_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='\u64cd\u4f5c\u4eba\u5458\u5907\u6ce8')),
                ('fail_reason', models.CharField(blank=True, default='', max_length=100, verbose_name='\u9000\u6b3e\u5931\u8d25\u539f\u56e0')),
                ('is_make', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u751f\u6210\u79ef\u5206')),
                ('belong_hotel', models.ForeignKey(blank=True, help_text='\u53ea\u6709\u5f53\u8ba2\u5355\u7c7b\u578b\u4e3a\u4f4f\u5bbf\u65f6\u624d\u4f1a\u6709\u6b64\u5b57\u6bb5', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Hotel')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='OrderPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_order_id', models.CharField(blank=True, default=0, max_length=32, null=True, verbose_name='\u5fae\u4fe1\u652f\u4ed8\u8ba2\u5355\u53f7')),
                ('free_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u514d\u8d39\u91d1\u989d')),
                ('integral', models.PositiveIntegerField(blank=True, default=0, verbose_name='\u652f\u4ed8\u79ef\u5206')),
                ('money', models.DecimalField(decimal_places=2, default=0, help_text='\u975e\u514d\u8d39\u91d1\u989d,\u5fae\u4fe1\u652f\u4ed8\u4e3a\u5b9e\u9645\u91d1\u989d, \u4f59\u989d\u652f\u4ed8\u4e3a\u4ece\u5145\u503c\u91d1\u989d\u6263\u53bb\u90e8\u5206', max_digits=10, verbose_name='\u91d1\u989d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pay', to='main.Order', verbose_name='\u8ba2\u5355\u652f\u4ed8\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u652f\u4ed8\u4fe1\u606f',
                'verbose_name_plural': '\u652f\u4ed8\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='OrderRefunded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_status', models.IntegerField(choices=[(10, '\u9000\u6b3e\u4e2d'), (20, '\u6210\u529f'), (30, '\u5931\u8d25'), (40, '\u91cd\u8bd5'), (50, '\u672a\u77e5')], default=50, help_text='\u9000\u6b3e\u72b6\u6001\u3002\u5fae\u4fe1\u53ef\u80fd\u4f1a\u9000\u6b3e\u5931\u8d25', verbose_name='\u9000\u6b3e\u72b6\u6001')),
                ('refunded_message', models.CharField(blank=True, default='', max_length=100, verbose_name='\u9000\u6b3e\u63cf\u8ff0')),
                ('refunded_order_id', models.CharField(default='', max_length=35, verbose_name='\u9000\u6b3e\u8ba2\u5355\u53f7')),
                ('refunded_money', models.DecimalField(decimal_places=2, default=0, help_text='\u5fae\u4fe1\u652f\u4ed8\u65f6,\u6b64\u91d1\u989d\u4e3a\u7528\u6237\u5fae\u4fe1\u652f\u4ed8\u91d1\u989d,\u4f59\u989d\u652f\u4ed8\u65f6\u4e3a\u5145\u503c\u91d1\u989d', max_digits=10, verbose_name='\u9000\u6b3e\u91d1\u989d')),
                ('refunded_free_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u9000\u6b3e\u8d60\u9001\u91d1\u989d')),
                ('refunded_integral', models.PositiveIntegerField(default=0, verbose_name='\u9000\u6b3e\u79ef\u5206')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('refunded_account', models.DateTimeField(blank=True, null=True, verbose_name='\u9000\u6b3e\u5230\u8d26\u65f6\u95f4')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_refunded', to='main.Order', verbose_name='\u5173\u8054\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u9000\u6b3e\u4fe1\u606f',
                'verbose_name_plural': '\u9000\u6b3e\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='RechargeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='\u5145\u503c\u8ba2\u5355\u53f7')),
                ('recharge_status', models.IntegerField(blank=True, choices=[(10, '\u6210\u529f'), (20, '\u53d6\u6d88'), (30, '\u7b49\u5f85\u652f\u4ed8')], default=30, verbose_name='\u5145\u503c\u72b6\u6001')),
                ('recharge_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5145\u503c\u91d1\u989d')),
                ('free_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u8d60\u9001\u91d1\u989d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5145\u503c\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u5145\u503c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='RechargeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u8d60\u9001\u4f59\u989d')),
                ('recharge_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5145\u503c\u91d1\u989d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u542f\u7528')),
            ],
            options={
                'verbose_name': '\u5145\u503c\u914d\u7f6e',
                'verbose_name_plural': '\u5145\u503c\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_nums', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='\u623f\u95f4\u7f16\u53f7')),
                ('room_status', models.IntegerField(choices=[(10, '\u672a\u5165\u4f4f'), (20, '\u5df2\u9884\u5b9a'), (30, '\u5165\u4f4f'), (40, '\u9000\u623f'), (50, '\u7ef4\u4fee')], default=10, verbose_name='\u623f\u95f4\u72b6\u6001')),
                ('reserve_time', models.DateTimeField(blank=True, help_text='\u9884\u5b9a\u65f6\u95f4', null=True, verbose_name='\u9884\u5b9a\u65f6\u95f4')),
                ('reserve_out_time', models.DateTimeField(blank=True, null=True, verbose_name='\u9884\u5b9a\u7ed3\u675f\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u623f\u95f4',
                'verbose_name_plural': '\u623f\u95f4',
            },
        ),
        migrations.CreateModel(
            name='RoomStyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='\u623f\u95f4\u7c7b\u578b')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5355\u4ef7')),
                ('room_profile', models.TextField(verbose_name='\u8be6\u60c5')),
                ('images', main.modelfields.JsonFields.JSONField(blank=True, default=[], verbose_name='\u56fe\u7247\u5217\u8868')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('cover_image', models.CharField(default='', max_length=100, verbose_name='\u5c01\u9762\u56fe')),
                ('room_count', models.PositiveIntegerField(default=0, verbose_name='\u623f\u95f4\u6570')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5bf9\u5916\u9500\u552e')),
                ('tags', main.modelfields.JsonFields.JSONField(default=[], verbose_name='\u6807\u7b7e')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('belong_hotel', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='room_styles', to='main.Hotel', verbose_name='\u6240\u5c5e\u9152\u5e97')),
            ],
            options={
                'verbose_name': '\u623f\u95f4\u7c7b\u578b',
                'verbose_name_plural': '\u623f\u95f4\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u4fe1\u606f')),
                ('sex', models.IntegerField(choices=[(10, '\u672a\u77e5'), (20, '\u7537'), (30, '\u5973')], default=10, verbose_name='\u6027\u522b')),
                ('belong_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Hotel', verbose_name='\u6240\u5c5e\u5bbe\u9986')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u5173\u8054\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u804c\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u804c\u5458\u4fe1\u606f',
                'permissions': [('banner', '\u6a2a\u5e45\u9875'), ('hotel', '\u5bbe\u9986\u4e2d\u5fc3'), ('consumer', '\u5ba2\u6237\u4e2d\u5fc3'), ('role', '\u6743\u9650\u4e2d\u5fc3'), ('distribution', '\u5206\u9500\u4e2d\u5fc3'), ('integral', '\u79ef\u5206\u4e2d\u5fc3'), ('market', '\u5546\u57ce\u4e2d\u5fc3'), ('market_order', '\u5546\u57ce\u8ba2\u5355\u4e2d\u5fc3'), ('tags', '\u6807\u7b7e\u4e2d\u5fc3'), ('staff', '\u804c\u5458\u4e2d\u5fc3'), ('hotel_order', '\u4f4f\u5bbf\u8ba2\u5355'), ('vip_info', '\u4f1a\u5458\u4e2d\u5fc3'), ('refunded', '\u9000\u6b3e\u4e2d\u5fc3'), ('comment_reply', '\u8bc4\u8bba\u56de\u590d\u4e2d\u5fc3')],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u6807\u7b7e\u540d\u79f0', max_length=20, unique=True, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('operator_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer', verbose_name='\u64cd\u4f5c\u4eba')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='UserRefundedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_express_id', models.CharField(max_length=100, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('user_express', models.CharField(max_length=100, verbose_name='\u5feb\u9012')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_refunded_info', to='main.Order', verbose_name='\u6240\u5c5e\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u9000\u8d27\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u9000\u8d27\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='VipMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_no', models.CharField(default='', max_length=32, unique=True, verbose_name='\u4f1a\u5458\u5361\u53f7')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u5bf9\u5e94\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u4f1a\u5458\u4e2d\u5fc3',
                'verbose_name_plural': '\u4f1a\u5458\u4e2d\u5fc3',
            },
        ),
        migrations.CreateModel(
            name='VipSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_name', models.CharField(max_length=10, unique=True, verbose_name='\u4f1a\u5458\u540d\u79f0')),
                ('vip_weight', models.IntegerField(default=0, help_text='\u5f53\u524d\u7528\u6237\u6743\u91cd,\u503c\u8d8a\u5927,\u4f18\u60e0\u6298\u6263\u66f4\u5927', verbose_name='\u4f1a\u5458\u6743\u91cd')),
                ('hotel_discount', models.DecimalField(decimal_places=2, help_text='\u9152\u5e97\u4f4f\u5bbf\u6298\u6263', max_digits=5, verbose_name='\u9152\u5e97\u6298\u6263')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('operator_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile')),
            ],
            options={
                'verbose_name': '\u4f1a\u5458\u6298\u6263\u914d\u7f6e',
                'verbose_name_plural': '\u4f1a\u5458\u6298\u6263\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='WeiXinPayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_order_id', models.CharField(blank=True, default='', help_text='\u968f\u673a\u751f\u6210', max_length=30, verbose_name='\u4f20\u9012\u7ed9\u8ba2\u5355\u53f7')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('call_back_result', models.CharField(blank=True, default='', max_length=20, verbose_name='\u56de\u8c03\u7ed3\u679c')),
                ('call_back_result_code', models.CharField(blank=True, default='', max_length=20, verbose_name='\u56de\u8c03\u4e1a\u52a1\u7ed3\u679c')),
                ('call_return_msg', models.CharField(blank=True, default='', max_length=100, verbose_name='\u56de\u8c03\u63cf\u8ff0')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Order')),
            ],
            options={
                'verbose_name': '\u5fae\u4fe1\u652f\u4ed8\u4fe1\u606f',
                'verbose_name_plural': '\u5fae\u4fe1\u652f\u4ed8\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='vipmember',
            name='vip_level',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.VipSettings'),
        ),
        migrations.AddField(
            model_name='roomstyles',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main.RoomStyles', verbose_name='\u623f\u95f4\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='rechargesettings',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StaffProfile', verbose_name='\u64cd\u4f5c\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='order',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile', verbose_name='\u64cd\u4f5c\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='notice',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StaffProfile', verbose_name='\u521b\u5efa\u4eba'),
        ),
        migrations.AddField(
            model_name='marketorderexpress',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_express', to='main.Order', verbose_name='\u8ba2\u5355'),
        ),
        migrations.AddField(
            model_name='marketorderdetail',
            name='market_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_order_detail', to='main.Order', verbose_name='\u5546\u573a\u8ba2\u5355'),
        ),
        migrations.AddField(
            model_name='marketordercontact',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_order_contact', to='main.Order'),
        ),
        migrations.AddField(
            model_name='integralsettings',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile'),
        ),
        migrations.AddField(
            model_name='images',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile', verbose_name='\u521b\u5efa\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='hotelorderdetail',
            name='hotel_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_order_detail', to='main.Order', verbose_name='\u6240\u5c5e\u8ba2\u5355'),
        ),
        migrations.AddField(
            model_name='hotelorderdetail',
            name='room_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RoomStyles', verbose_name='\u623f\u95f4\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='hotelordercomment',
            name='belong_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='\u5173\u8054\u8ba2\u5355'),
        ),
        migrations.AddField(
            model_name='hotelordercomment',
            name='commenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u8bc4\u8bba\u4eba'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile', verbose_name='\u64cd\u4f5c\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='growthvaluesettings',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile'),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='main.GoodsCategory', verbose_name='\u5546\u54c1\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='goods',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile'),
        ),
        migrations.AddField(
            model_name='goods',
            name='vip_info',
            field=models.OneToOneField(blank=True, help_text='\u4f1a\u5458\u6743\u76ca', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.VipSettings'),
        ),
        migrations.AddField(
            model_name='distributionbonuspick',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile', verbose_name='\u64cd\u4f5c\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='distributionbonusdetail',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile'),
        ),
        migrations.AddField(
            model_name='distributionbonusdetail',
            name='pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.DistributionBonusPick', verbose_name='\u63d0\u53d6\u5173\u8054\u7533\u8bf7'),
        ),
        migrations.AddField(
            model_name='distributionapply',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile'),
        ),
        migrations.AddField(
            model_name='consumerbalance',
            name='recharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.RechargeInfo'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='main.HotelOrderComment'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='reply_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StaffProfile', verbose_name='\u56de\u590d\u4eba'),
        ),
        migrations.AddField(
            model_name='cart',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Consumer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Goods', verbose_name='\u5546\u54c1'),
        ),
        migrations.AddField(
            model_name='banners',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile'),
        ),
        migrations.AddField(
            model_name='adminrefundedinfo',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_refunded_info', to='main.Order', verbose_name='\u9000\u6b3e\u5730\u5740'),
        ),
    ]
