# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=100, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u5546\u54c1\u4ef7\u683c')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('category_name', models.CharField(max_length=10, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('is_active', models.BooleanField(default=False, help_text='\u9ed8\u8ba4\u4e0d\u4e0a\u67b6', verbose_name='\u662f\u5426\u4e0a\u67b6')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u5206\u7c7b',
                'verbose_name_plural': '\u5546\u54c1\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5bbe\u9986\u540d\u79f0')),
                ('address', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
                ('longitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7ecf\u5ea6')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7eac\u5ea6')),
                ('hotel_profile', models.TextField(verbose_name='\u5bbe\u9986\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': '\u5bbe\u9986\u4fe1\u606f',
                'verbose_name_plural': '\u5bbe\u9986\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ImagesModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u56fe\u7247')),
                ('order_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '\u56fe\u7247',
                'verbose_name_plural': '\u56fe\u7247',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GoodsCategory', verbose_name='\u5546\u54c1\u5206\u7c7b'),
        ),
    ]
