# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-14 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
