# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-14 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180814_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='goods', to='main.GoodsCategory', verbose_name='\u5546\u54c1\u5206\u7c7b'),
        ),
    ]
