# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181120_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargeinfo',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='\u5145\u503c\u8ba2\u5355\u53f7'),
        ),
    ]
