# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-14 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180814_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e0a\u67b6'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='main.GoodsCategory', verbose_name='\u5546\u54c1\u5206\u7c7b'),
        ),
    ]
