# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181121_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionbonusdetail',
            name='buyers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='main.Consumer'),
        ),
    ]
