# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-18 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20180814_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='\u7528\u6237\u59d3\u540d')),
                ('sex', models.IntegerField(choices=[(10, 'unknown'), (20, 'male'), (30, 'female')], default=10, verbose_name='\u6027\u522b')),
                ('phone', models.CharField(blank='', default='', max_length=15, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('contact_addr', models.CharField(blank='', default='', max_length=100, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u6d88\u8d39\u8005\u4fe1\u606f',
                'verbose_name_plural': '\u6d88\u8d39\u8005\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='GrowthValueSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_growth_value', models.PositiveIntegerField(default=0, verbose_name='\u6700\u5c0f\u6210\u957f\u503c')),
                ('max_growth_value', models.PositiveIntegerField(default=2147483648, help_text='2147483647', verbose_name='\u6700\u5927\u6210\u957f\u503c')),
                ('level', models.CharField(help_text='\u6210\u957f\u503c\u5bf9\u5e94\u7b49\u7ea7', max_length=10, verbose_name='\u7b49\u7ea7')),
            ],
            options={
                'verbose_name': '\u6210\u957f\u503c\u5bf9\u5e94\u7b49\u7ea7',
                'verbose_name_plural': '\u6210\u957f\u503c\u5bf9\u5e94\u7b49\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='Integral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral', models.PositiveIntegerField(default=0, help_text='\u79ef\u5206\u53ef\u4ee5\u7528\u4e8e\u5151\u6362\u7269\u54c1', verbose_name='\u603b\u79ef\u5206')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('growth_value', models.PositiveIntegerField(default=0, help_text='\u6210\u957f\u503c\u7b49\u4e8e\u6240\u6709\u79ef\u5206', verbose_name='\u6210\u957f\u503c')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u79ef\u5206',
                'verbose_name_plural': '\u7528\u6237\u79ef\u5206',
            },
        ),
        migrations.CreateModel(
            name='IntegralDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral', models.IntegerField(default=0, verbose_name='\u79ef\u5206\u60c5\u51b5')),
                ('remark', models.CharField(blank=True, default='', help_text='\u672c\u6b21\u79ef\u5206\u6765\u6e90', max_length=100, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='\u6d88\u8d39\u65f6\u95f4', verbose_name='\u6d88\u8d39\u65f6\u95f4')),
                ('left_integral', models.IntegerField(default=0, verbose_name='\u5269\u4f59\u79ef\u5206')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u79ef\u5206\u660e\u7ec6',
                'verbose_name_plural': '\u79ef\u5206\u660e\u7ec6',
            },
        ),
        migrations.CreateModel(
            name='IntegralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral', models.PositiveIntegerField(verbose_name='\u79ef\u5206\u914d\u7f6e\uff081\u5143\u7b49\u4e8e\u591a\u5c11\u79ef\u5206\uff09')),
            ],
            options={
                'verbose_name': '\u79ef\u5206\u914d\u7f6e',
                'verbose_name_plural': '\u79ef\u5206\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, verbose_name='\u8ba2\u5355\u53f7')),
                ('order_statue', models.IntegerField(blank=True, choices=[(10, '\u672a\u652f\u4ed8'), (20, '\u5f85\u53d1\u8d27'), (30, '\u5f85\u6536\u8d27'), (40, '\u5df2\u5b8c\u6210'), (50, '\u5df2\u53d6\u6d88')], default=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('operator_time', models.DateTimeField(blank=True, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('user_remark', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u7528\u6237\u5907\u6ce8')),
                ('operator_remark', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u64cd\u4f5c\u4eba\u5458\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u5546\u573a\u8ba2\u5355',
                'verbose_name_plural': '\u5546\u573a\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='MarketOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u9500\u552e\u5355\u4ef7')),
                ('nums', models.PositiveIntegerField(default=0, verbose_name='\u8d2d\u4e70\u6570\u91cf')),
            ],
            options={
                'verbose_name': '\u5546\u573a\u8ba2\u5355\u660e\u7ec6',
                'verbose_name_plural': '\u5546\u573a\u8ba2\u5355\u660e\u7ec6',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='is_integral',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u53ef\u4ee5\u79ef\u5206\u5151\u6362'),
        ),
        migrations.AddField(
            model_name='goods',
            name='need_integral',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='\u6240\u9700\u6700\u5927\u79ef\u5206'),
        ),
        migrations.AddField(
            model_name='marketorderdetail',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='main.Goods', verbose_name='\u5546\u54c1\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='marketorderdetail',
            name='market_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_order', to='main.MarketOrder', verbose_name='\u5546\u573a\u8ba2\u5355'),
        ),
    ]
