# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180818_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='sex',
            field=models.IntegerField(choices=[(10, '\u4e3a\u6b62'), (20, '\u7537'), (30, '\u5973')], default=10, verbose_name='\u6027\u522b'),
        ),
    ]
