# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-24 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_distributionbonusdetail_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='distribution_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='\u56fa\u5b9a\u6bd4\u4f8b\u5206\u9500\u5956\u91d1', max_digits=10, verbose_name='\u5206\u9500\u5956\u91d1'),
        ),
        migrations.AddField(
            model_name='goods',
            name='distribution_method',
            field=models.CharField(choices=[('no', '\u4e0d\u53c2\u4e0e'), ('fixed', '\u56fa\u5b9a'), ('ratio', '\u6bd4\u4f8b')], default='no', max_length=10, verbose_name='\u5206\u9500\u65b9\u5f0f'),
        ),
        migrations.AddField(
            model_name='goods',
            name='distribution_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='\u5206\u9500\u6bd4\u4f8b', max_digits=2, verbose_name='\u5206\u9500\u6bd4\u4f8b'),
        ),
    ]
