# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-18 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180818_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integraldetail',
            old_name='user',
            new_name='consumer',
        ),
    ]
