# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181124_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='distribution_bonus',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='distribution_ratio',
        ),
        migrations.RemoveField(
            model_name='roomstyles',
            name='distribution_bonus',
        ),
        migrations.RemoveField(
            model_name='roomstyles',
            name='distribution_ratio',
        ),
        migrations.AddField(
            model_name='goods',
            name='distribution_calc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='\u5206\u9500\u91d1\u989d\u8ba1\u7b97\uff0c\u5982\u679c\u662f\u56fa\u5b9a\u662f\u5355\u4ef6\u5546\u54c1\u4ef7\u683c\uff0c\u5982\u679c\u662f\u6bd4\u4f8b\u8fd9\u662f\u9500\u552e\u4ef7\u683c\u7684\u6bd4\u4f8b', max_digits=10, verbose_name='\u5206\u9500\u5956\u91d1'),
        ),
        migrations.AddField(
            model_name='roomstyles',
            name='distribution_calc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='\u5206\u9500\u91d1\u989d\u8ba1\u7b97\uff0c\u5982\u679c\u662f\u56fa\u5b9a\u662f\u5355\u4ef6\u5546\u54c1\u4ef7\u683c\uff0c\u5982\u679c\u662f\u6bd4\u4f8b\u8fd9\u662f\u9500\u552e\u4ef7\u683c\u7684\u6bd4\u4f8b', max_digits=10, verbose_name='\u5206\u9500\u5956\u91d1'),
        ),
    ]
