# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-23 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.modelfields.JsonFields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180818_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8ba2\u5355\u53f7')),
                ('order_status', models.IntegerField(verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('room_style_num', models.PositiveIntegerField(default=0, help_text='\u7528\u4e8e', verbose_name='\u623f\u95f4\u7c7b\u578b\u6570\u91cf')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u8ba2\u5355\u91d1\u989d')),
                ('reserve_check_in_time', models.DateTimeField(help_text='\u7528\u6237\u9884\u5b9a\u65f6\u95f4\uff0c12\u70b9\u4ee5\u540e', verbose_name='\u9884\u5b9a\u5165\u4f4f\u65f6\u95f4')),
                ('reserve_check_out_time', models.DateTimeField(help_text='\u7528\u6237\u9884\u5b9a\u65f6\u95f4', verbose_name='\u9884\u5b9a\u9000\u623f\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('operator_time', models.DateTimeField(auto_now=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('user_remark', models.TextField(blank=True, default='', verbose_name='\u7528\u6237\u5907\u6ce8')),
                ('flow_remark', models.TextField(blank=True, default='', help_text='\u7ba1\u7406\u4eba\u5458\u5907\u6ce8', verbose_name='\u8ddf\u8fdb\u5907\u6ce8')),
                ('belong_hotel', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Hotel', verbose_name='\u6240\u5c5e\u5bbe\u9986')),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='HotelOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_nums', models.PositiveIntegerField(default=0, verbose_name='\u623f\u95f4\u6570\u91cf')),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u5165\u4f4f\u65f6\u623f\u95f4\u5355\u4ef7')),
                ('belong_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_order_detail', to='main.HotelOrder', verbose_name='\u6240\u5c5e\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u623f\u95f4\u8be6\u60c5',
                'verbose_name_plural': '\u8ba2\u5355\u623f\u95f4\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='HotelOrderRoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='\u7528\u6237\u5165\u4f4f\u65f6\u95f4')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='\u9000\u623f\u65f6\u95f4')),
                ('guest_nums', models.PositiveIntegerField(blank=True, default=0, verbose_name='\u5165\u4f4f\u4eba\u6570')),
                ('guest_info', main.modelfields.JsonFields.JSONField(help_text='\u591a\u4e2a\u7528\u6237\u4fe1\u606f\u653e\u5165\u3002\u5b58\u5165\u6570\u636e\u5e93\u4e3astring', verbose_name='\u7528\u6237\u4fe1\u606f')),
                ('belong_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HotelOrder', verbose_name='\u8ba2\u5355\u53f7')),
            ],
            options={
                'verbose_name': '\u5165\u4f4f\u4fe1\u606f',
                'verbose_name_plural': '\u5165\u4f4f\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_nums', models.CharField(max_length=20, verbose_name='\u623f\u95f4\u7f16\u53f7')),
                ('room_status', models.IntegerField(choices=[(10, '\u672a\u5165\u4f4f'), (20, '\u5df2\u9884\u5b9a'), (30, '\u5165\u4f4f'), (40, '\u9000\u623f')], default=10, verbose_name='\u623f\u95f4\u72b6\u6001')),
                ('reserve_time', models.DateTimeField(blank=True, help_text='\u9884\u5b9a\u65f6\u95f4', null=True, verbose_name='\u9884\u5b9a\u65f6\u95f4')),
                ('reserve_out_time', models.DateTimeField(blank=True, null=True, verbose_name='\u9884\u5b9a\u7ed3\u675f\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u623f\u95f4',
                'verbose_name_plural': '\u623f\u95f4',
            },
        ),
        migrations.CreateModel(
            name='RoomStyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, default='', verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('style_name', models.CharField(db_index=True, max_length=100, verbose_name='\u623f\u95f4\u7c7b\u578b')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u5355\u4ef7')),
                ('room_profile', models.TextField(verbose_name='\u8be6\u60c5')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5bf9\u5916\u9500\u552e')),
                ('belong_hotel', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Hotel', verbose_name='\u6240\u5c5e\u9152\u5e97')),
            ],
            options={
                'verbose_name': '\u623f\u95f4\u7c7b\u578b',
                'verbose_name_plural': '\u623f\u95f4\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main.RoomStyles', verbose_name='\u623f\u95f4\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='hotelorderroominfo',
            name='check_in_room',
            field=models.ForeignKey(help_text='\u8fd9\u91cc\u5165\u4f4f\u65f6,\u9700\u8981\u628a\u5173\u8054\u623f\u95f4\u72b6\u6001\u66f4\u6539\u4e3a\u5165\u4f4f', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Rooms', verbose_name='\u5165\u4f4f\u623f\u95f4'),
        ),
        migrations.AddField(
            model_name='hotelorderdetail',
            name='room_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RoomStyles', verbose_name='\u623f\u95f4\u7c7b\u578b'),
        ),
    ]
