# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-23 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180823_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='\u5bbe\u9986\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='roomstyles',
            name='create_time',
            field=models.DateTimeField(auto_created=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
