# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180823_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstyles',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
