# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import main.modelfields.JsonFields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180828_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('banner_images', models.CharField(help_text='\u5b58\u50a8\u7edd\u5bf9\u8def\u5f84', max_length=300, verbose_name='\u6a2a\u5e45\u56fe\u7247')),
                ('jump_url', models.CharField(blank=True, help_text='\u5b58\u50a8\u7edd\u5bf9\u8def\u5f84', max_length=300, null=True, verbose_name='\u8df3\u8f6c\u8fde\u63a5')),
                ('is_show', models.BooleanField(default=False, help_text='\u662f\u5426\u53ef\u7528\u5728\u524d\u7aef\u5c55\u793a', verbose_name='\u662f\u5426\u5c55\u793a')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banner',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u56fe\u7247',
                'verbose_name_plural': '\u56fe\u7247',
            },
        ),
        migrations.RemoveField(
            model_name='imagesmodels',
            name='content_type',
        ),
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=main.modelfields.JsonFields.JSONField(blank=True, default='[]', help_text='\u56fe\u7247\uff0c\u5b58\u653e\u56fe\u7247\u7684URL', null=True, verbose_name='\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='roomstyles',
            name='images',
            field=main.modelfields.JsonFields.JSONField(default='[]', verbose_name='\u56fe\u7247\u5217\u8868'),
        ),
        migrations.DeleteModel(
            name='ImagesModels',
        ),
    ]
