# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180828_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelorder',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(10, '\u5f85\u652f\u4ed8'), (20, '\u5f85\u5165\u4f4f'), (30, '\u5165\u4f4f\u4e2d'), (40, '\u5b8c\u6210'), (50, '\u5f85\u8bc4\u4ef7'), (60, '\u53d6\u6d88'), (70, '\u5f85\u9000\u6b3e'), (80, '\u5df2\u9000\u6b3e')], default=10, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='hotelorderroominfo',
            name='belong_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_order_room_info', to='main.HotelOrder', verbose_name='\u8ba2\u5355\u53f7'),
        ),
    ]
