# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.modelfields.JsonFields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180828_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_status', models.IntegerField(choices=[(10, '\u63d0\u4ea4\u6210\u529f'), (20, '\u53d7\u7406\u4e2d'), (30, '\u53d7\u7406\u5b8c\u6210'), (40, '\u64a4\u56de\u7533\u8bf7')], default=10, verbose_name='\u7533\u8bf7\u72b6\u6001')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('apply_remark', models.CharField(max_length=520, verbose_name='\u7533\u8bf7\u539f\u56e0')),
                ('success_time', models.DateTimeField(blank=True, null=True, verbose_name='\u6210\u529f\u65f6\u95f4')),
                ('operator_time', models.DateTimeField(auto_now=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('is_success', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7533\u8bf7\u6210\u529f')),
                ('fail_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='\u5931\u8d25\u539f\u56e0')),
            ],
            options={
                'verbose_name': '\u5206\u9500\u7533\u8bf7\u8bb0\u5f55',
                'verbose_name_plural': '\u5206\u9500\u7533\u8bf7\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='DistributionBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5206\u9500\u5956\u91d1')),
                ('operator_time', models.DateTimeField(auto_now=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5206\u9500\u5956\u91d1',
                'verbose_name_plural': '\u5206\u9500\u5956\u91d1',
            },
        ),
        migrations.CreateModel(
            name='DistributionBonusDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_bonus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5269\u4f59\u5956\u91d1')),
                ('bonus_detail', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4f7f\u7528\u91d1\u989d')),
                ('remark', models.CharField(max_length=100, verbose_name='\u4f7f\u7528\u539f\u56e0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('operator_time', models.DateTimeField(auto_now=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5206\u9500\u5956\u91d1\u660e\u7ec6',
                'verbose_name_plural': '\u5206\u9500\u5956\u91d1\u660e\u7ec6',
            },
        ),
        migrations.CreateModel(
            name='DistributionBonusPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u63d0\u53d6\u91d1\u989d')),
                ('pick_time', models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('success_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('transfer_time', models.DateTimeField(blank=True, null=True, verbose_name='\u8f6c\u8d26\u65f6\u95f4')),
                ('fail_remark', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='\u5931\u8d25\u539f\u56e0')),
            ],
            options={
                'verbose_name': '\u63d0\u53d6\u5206\u9500\u91d1\u989d\u7533\u8bf7',
                'verbose_name_plural': '\u63d0\u53d6\u5206\u9500\u91d1\u989d\u7533\u8bf7',
            },
        ),
        migrations.AddField(
            model_name='consumer',
            name='is_distribution',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5206\u9500\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='sell_user',
            field=models.ForeignKey(blank=True, help_text='\u63a8\u9500\u4eba', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer'),
        ),
        migrations.AlterField(
            model_name='hotelorderroominfo',
            name='guest_info',
            field=main.modelfields.JsonFields.JSONField(default='[]', help_text='\u591a\u4e2a\u7528\u6237\u4fe1\u606f\u653e\u5165\u3002\u5b58\u5165\u6570\u636e\u5e93\u4e3astring', verbose_name='\u7528\u6237\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_nums',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='\u623f\u95f4\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='distributionbonuspick',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer'),
        ),
        migrations.AddField(
            model_name='distributionbonusdetail',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_bonus_detail', to='main.Consumer'),
        ),
        migrations.AddField(
            model_name='distributionbonus',
            name='consumer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_bonus', to='main.Consumer'),
        ),
        migrations.AddField(
            model_name='distributionapply',
            name='consumer',
            field=models.ForeignKey(blank=True, help_text='\u7528\u6237', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer'),
        ),
    ]
