# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-30 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180830_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionbonuspick',
            name='pick_status',
            field=models.IntegerField(blank=True, choices=[(10, '\u63d0\u4ea4\u7533\u8bf7'), (20, '\u6b63\u5728\u5904\u7406'), (30, '\u8f6c\u8d26\u4e2d'), (40, '\u5b8c\u6210'), (50, '\u63d0\u53d6\u5931\u8d25'), (60, '\u53d6\u6d88\u7533\u8bf7')], default=10, verbose_name='\u63d0\u53d6\u72b6\u6001'),
        ),
    ]
