# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-01 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_distributionbonuspick_pick_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionbonusdetail',
            name='pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.DistributionBonusPick', verbose_name='\u63d0\u53d6\u5173\u8054\u7533\u8bf7'),
        ),
        migrations.AddField(
            model_name='distributionbonusdetail',
            name='status',
            field=models.IntegerField(blank=True, choices=[(10, '\u672a\u77e5'), (20, '\u6210\u529f'), (30, '\u5931\u8d25'), (40, '\u53d6\u6d88')], default=10, verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='integralsettings',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integralsettings',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u94b1'),
        ),
        migrations.AddField(
            model_name='integralsettings',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='integralsettings',
            name='integral',
            field=models.PositiveIntegerField(verbose_name='\u79ef\u5206'),
        ),
    ]
