# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180901_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionbonus',
            name='consumer',
        ),
        migrations.AddField(
            model_name='consumer',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='\u5206\u9500\u5956\u91d1'),
        ),
        migrations.DeleteModel(
            name='DistributionBonus',
        ),
    ]
