# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-05 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180905_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionbonusdetail',
            name='detail_type',
            field=models.IntegerField(default=0, help_text='\u5956\u91d1\u660e\u7ec6\u7c7b\u578b', verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='distributionbonusdetail',
            name='use_bonus',
            field=models.DecimalField(decimal_places=2, help_text='\u6d88\u8d39\u91d1\u989d', max_digits=10, verbose_name='\u4f7f\u7528\u91d1\u989d'),
        ),
    ]
