# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180905_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5fae\u4fe1openid'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5fae\u4fe1\u56de\u8bddkey'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='sex',
            field=models.IntegerField(choices=[(10, '\u672a\u77e5'), (20, '\u7537'), (30, '\u5973')], default=10, verbose_name='\u6027\u522b'),
        ),
    ]
