# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-08 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180906_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketorder',
            old_name='order_statue',
            new_name='order_status',
        ),
        migrations.AddField(
            model_name='marketorder',
            name='consignee_address',
            field=models.CharField(default='', max_length=200, verbose_name='\u6536\u8d27\u4eba\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='marketorder',
            name='consignee_name',
            field=models.CharField(default='', max_length=50, verbose_name='\u6536\u8d27\u4eba\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='marketorder',
            name='consignee_phone',
            field=models.CharField(default='', max_length=15, verbose_name='\u6536\u8d27\u4eba\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='marketorder',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer'),
        ),
        migrations.AlterField(
            model_name='marketorderdetail',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='main.Goods', verbose_name='\u5546\u54c1\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='marketorderdetail',
            name='market_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_order', to='main.MarketOrder', verbose_name='\u5546\u573a\u8ba2\u5355'),
        ),
    ]
