# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180908_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.AddField(
            model_name='hotel',
            name='area',
            field=models.CharField(default='', max_length=100, verbose_name='\u533a'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='\u6210\u90fd\u5e02', max_length=20, verbose_name='\u5e02'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cover_images',
            field=models.CharField(default='', max_length=100, verbose_name='\u5c01\u9762\u56fe'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='province',
            field=models.CharField(default='\u56db\u5ddd\u7701', max_length=100, verbose_name='\u7701\u4efd'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street',
            field=models.CharField(default='', max_length=200, verbose_name='\u8857\u9053\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='marketorderdetail',
            name='market_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_order_detail', to='main.MarketOrder', verbose_name='\u5546\u573a\u8ba2\u5355'),
        ),
        migrations.AlterField(
            model_name='roomstyles',
            name='belong_hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='room_styles', to='main.Hotel', verbose_name='\u6240\u5c5e\u9152\u5e97'),
        ),
    ]
