# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180909_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.CharField(default='', max_length=100, verbose_name='\u7eac\u5ea6'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.CharField(default='', max_length=100, verbose_name='\u7ecf\u5ea6'),
        ),
    ]
