# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-10 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180910_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstyles',
            name='cover_image',
            field=models.CharField(default='', max_length=100, verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
