# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-10 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0025_roomstyles_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u4fe1\u606f')),
                ('sex', models.IntegerField(choices=[(10, '\u672a\u77e5'), (20, '\u7537'), (30, '\u5973')], default=10, verbose_name='\u6027\u522b')),
                ('belong_hotel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Hotel', verbose_name='\u6240\u5c5e\u5bbe\u9986')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u5173\u8054\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u804c\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u804c\u5458\u4fe1\u606f',
            },
        ),
    ]
