# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tel',
            field=models.CharField(default='', max_length=50, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
    ]
