# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-11 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180911_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='operator_time',
            new_name='operator_name',
        ),
        migrations.AddField(
            model_name='marketorder',
            name='pay_type',
            field=models.IntegerField(choices=[(10, '\u79ef\u5206'), (20, '\u91d1\u94b1')], default=20, help_text='\u9ed8\u8ba4\u91d1\u94b1\u652f\u4ed8', verbose_name='\u652f\u4ed8\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='need_integral',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='\u6240\u9700\u79ef\u5206'),
        ),
    ]
