# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180911_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerVipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_start_time', models.DateTimeField(verbose_name='\u4f1a\u5458\u6709\u6548\u671f')),
                ('vip_end_time', models.DateTimeField(verbose_name='\u4f1a\u5458\u5931\u6548\u671f')),
            ],
            options={
                'verbose_name': '\u5ba2\u6237\u4f1a\u5458\u7cfb\u7edf',
                'verbose_name_plural': '\u5ba2\u6237\u4f1a\u5458\u7cfb\u7edf',
            },
        ),
        migrations.AddField(
            model_name='consumer',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u4f1a\u5458'),
        ),
        migrations.AddField(
            model_name='marketorder',
            name='pay_integral',
            field=models.PositiveIntegerField(default=0, help_text='\u5f53\u652f\u4ed8\u65b9\u5f0f\u4e3a\u79ef\u5206\u65f6', verbose_name='\u6d88\u8d39\u79ef\u5206'),
        ),
        migrations.AddField(
            model_name='marketorder',
            name='pay_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='\u652f\u4ed8\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='marketorderdetail',
            name='integral',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='\u5151\u6362\u79ef\u5206\u5355\u4ef7'),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='pay_type',
            field=models.IntegerField(choices=[(10, '\u79ef\u5206'), (20, '\u91d1\u94b1'), (30, '\u6df7\u5408')], default=20, help_text='\u9ed8\u8ba4\u91d1\u94b1\u652f\u4ed8', verbose_name='\u652f\u4ed8\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='marketorderdetail',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='\u9500\u552e\u5355\u4ef7'),
        ),
        migrations.AddField(
            model_name='consumervipinfo',
            name='consumer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_info', to='main.Consumer'),
        ),
    ]
