# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-17 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20180912_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstyles',
            name='room_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u623f\u95f4\u6570'),
        ),
    ]
