# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-25 21:40
from __future__ import unicode_literals

from django.db import migrations
import main.modelfields.JsonFields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_roomstyles_room_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tags',
            field=main.modelfields.JsonFields.JSONField(blank=True, default='[]', help_text='\u6807\u7b7e,\u5b58\u653e\u4e3a\u6570\u7ec4,\u6570\u636e\u5e93\u4e3ajson\u540e\u7684list', verbose_name='\u6807\u7b7e\u7ba1\u7406'),
        ),
    ]
