# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-26 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_hotel_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.IntegerField(choices=[(10, '\u5145\u503c'), (20, '\u6d88\u8d39')], default=10, verbose_name='\u4f59\u989d\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4f59\u989d\u8be6\u60c5',
                'verbose_name_plural': '\u7528\u6237\u4f59\u989d\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xe6\xa0\x87\xe7\xad\xbe\xe5\x90\x8d\xe7\xa7\xb0', max_length=20, unique=True, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='consumer',
            name='free_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='\u5145\u503c\u8d60\u9001\u91d1\u989d', max_digits=10, verbose_name='\u5956\u52b1\u91d1'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='recharge_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='\u5145\u503c\u4f59\u989d', max_digits=10, verbose_name='\u4f59\u989d'),
        ),
        migrations.AddField(
            model_name='integraldetail',
            name='integral_type',
            field=models.IntegerField(choices=[(10, '\u589e\u52a0'), (20, '\u6d88\u8d39')], default=10, verbose_name='\u79ef\u5206\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='hotelorder',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u8ba2\u5355\u91d1\u989d'),
        ),
        migrations.AlterField(
            model_name='hotelorderdetail',
            name='room_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u5165\u4f4f\u65f6\u623f\u95f4\u5355\u4ef7'),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='pay_type',
            field=models.IntegerField(choices=[(10, '\u79ef\u5206'), (20, '\u4f59\u989d'), (30, '\u5fae\u4fe1\u652f\u4ed8')], default=30, help_text='\u9ed8\u8ba4\u5fae\u4fe1\u652f\u4ed8', verbose_name='\u652f\u4ed8\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='marketorderdetail',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Goods'),
        ),
        migrations.AlterField(
            model_name='marketorderdetail',
            name='market_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MarketOrder', verbose_name='\u5546\u573a\u8ba2\u5355'),
        ),
        migrations.AddField(
            model_name='tags',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer', verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe4\xba\xba'),
        ),
        migrations.AddField(
            model_name='consumerbalance',
            name='consumer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u5bf9\u5e94\u7528\u6237'),
        ),
    ]
