# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-26 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20180926_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelorder',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer', verbose_name='\u7528\u6237'),
        ),
    ]
