# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-26 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20180926_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelorder',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u8ba2\u5355\u91d1\u989d'),
        ),
    ]
