# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-27 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20180926_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerbalance',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='\u6b63\u6570\u4ee3\u8868\u4e3a\u5145\u503c\u3002\u8d1f\u6570\u4ee3\u8868\u6d88\u8d39', max_digits=10, verbose_name='\u6d88\u8d39\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='consumerbalance',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u6d88\u8d39\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerbalance',
            name='left_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='\u7528\u6237\u5269\u4f59\u4f59\u989d', max_digits=10, verbose_name='\u5269\u4f59\u4f59\u989d'),
        ),
        migrations.AddField(
            model_name='consumerbalance',
            name='message',
            field=models.CharField(default=0, max_length=30, verbose_name='\u6d88\u8d39\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='consumerbalance',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u5bf9\u5e94\u7528\u6237'),
        ),
    ]
