# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-01 21:48
from __future__ import unicode_literals

from django.db import migrations
import main.modelfields.JsonFields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20180928_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='tags',
            field=main.modelfields.JsonFields.JSONField(blank=True, default=[], help_text='\u6807\u7b7e,\u5b58\u653e\u4e3a\u6570\u7ec4,\u6570\u636e\u5e93\u4e3ajson\u540e\u7684list', verbose_name='\u6807\u7b7e\u7ba1\u7406'),
        ),
        migrations.AlterField(
            model_name='roomstyles',
            name='images',
            field=main.modelfields.JsonFields.JSONField(default=[], verbose_name='\u56fe\u7247\u5217\u8868'),
        ),
    ]
