# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-03 15:41
from __future__ import unicode_literals

from django.db import migrations
import main.modelfields.JsonFields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20181001_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstyles',
            name='images',
            field=main.modelfields.JsonFields.JSONField(blank=True, default=[], verbose_name='\u56fe\u7247\u5217\u8868'),
        ),
    ]
