# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-03 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20181003_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='\u5145\u503c\u8ba2\u5355\u53f7')),
                ('recharge_money', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u5145\u503c\u91d1\u989d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5145\u503c\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u5145\u503c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='RechargeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_balance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u8d60\u9001\u4f59\u989d')),
                ('recharge_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u5145\u503c\u91d1\u989d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u542f\u7528')),
                ('operator_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StaffProfile', verbose_name='\u64cd\u4f5c\u4eba\u5458')),
            ],
            options={
                'verbose_name': '\u5145\u503c\u914d\u7f6e',
                'verbose_name_plural': '\u5145\u503c\u914d\u7f6e',
            },
        ),
        migrations.AddField(
            model_name='consumerbalance',
            name='recharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.RechargeInfo'),
        ),
    ]
