# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-04 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20181003_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeinfo',
            name='free_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='\u8d60\u9001\u91d1\u989d'),
        ),
        migrations.AddField(
            model_name='rechargeinfo',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u652f\u4ed8\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='rechargeinfo',
            name='recharge_status',
            field=models.IntegerField(blank=True, choices=[(10, '\u6210\u529f'), (20, '\u53d6\u6d88'), (30, '\u7b49\u5f85\u652f\u4ed8')], default=30, verbose_name='\u5145\u503c\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='hotelorder',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(10, '\u5f85\u652f\u4ed8'), (20, '\u5f85\u5165\u4f4f'), (30, '\u5165\u4f4f\u4e2d'), (40, '\u5b8c\u6210'), (50, '\u5f85\u8bc4\u4ef7'), (60, '\u53d6\u6d88'), (70, '\u5f85\u9000\u6b3e'), (80, '\u5df2\u9000\u6b3e'), (90, '\u5df2\u8fc7\u671f')], default=10, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='rechargeinfo',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Consumer', verbose_name='\u7528\u6237'),
        ),
    ]
