# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-07 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20181004_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='user_name',
            field=models.CharField(default='', max_length=30, verbose_name='\u7528\u6237\u59d3\u540d'),
        ),
    ]
