# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20181007_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelordercomment',
            options={'verbose_name': '\u8ba2\u5355\u8bc4\u8bba', 'verbose_name_plural': '\u8ba2\u5355\u8bc4\u8bba'},
        ),
        migrations.AddField(
            model_name='goods',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4fc3\u9500'),
        ),
    ]
