# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-08 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20181008_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionbonuspick',
            name='bank',
            field=models.CharField(default='', help_text='\u5f53\u63d0\u53d6\u65b9\u5f0f\u4e3a\u94f6\u884c\u5361\u65f6,\u6b64\u5b57\u6bb5\u5fc5\u987b\u8f93\u5165', max_length=100, verbose_name='\u5f00\u6237\u884c'),
        ),
        migrations.AddField(
            model_name='distributionbonuspick',
            name='transfer_account',
            field=models.CharField(default='', max_length=100, verbose_name='\u8f6c\u8d26\u8d26\u53f7'),
        ),
        migrations.AddField(
            model_name='distributionbonuspick',
            name='transfer_type',
            field=models.IntegerField(choices=[(10, '\u652f\u4ed8\u5b9d'), (20, '\u5fae\u4fe1'), (30, '\u94f6\u884c\u5361')], default=10, verbose_name='\u8f6c\u8d26\u65b9\u5f0f'),
        ),
    ]
