# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-08 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20181008_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelordercomment',
            name='belong_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.HotelOrder', verbose_name='\u5173\u8054\u8ba2\u5355'),
        ),
        migrations.AlterField(
            model_name='hotelorderdetail',
            name='room_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5165\u4f4f\u65f6\u623f\u95f4\u5355\u4ef7'),
        ),
    ]
