# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-09 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20181008_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'permissions': [('banner', '\u6a2a\u5e45\u9875'), ('hotel', '\u5bbe\u9986\u4e2d\u5fc3'), ('consumer', '\u5ba2\u6237\u4e2d\u5fc3'), ('groups', '\u6743\u9650\u4e2d\u5fc3'), ('distribution', '\u5206\u9500\u4e2d\u5fc3'), ('integral', '\u79ef\u5206\u4e2d\u5fc3'), ('market', '\u5546\u57ce\u4e2d\u5fc3'), ('market_order', '\u5546\u57ce\u8ba2\u5355\u4e2d\u5fc3'), ('tags', '\u6807\u7b7e\u4e2d\u5fc3'), ('staff', '\u804c\u5458\u4e2d\u5fc3')], 'verbose_name': '\u804c\u5458\u4fe1\u606f', 'verbose_name_plural': '\u804c\u5458\u4fe1\u606f'},
        ),
    ]
