# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-09 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20181009_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='belong_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Hotel', verbose_name='\u6240\u5c5e\u5bbe\u9986'),
        ),
    ]
