# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-12 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20181010_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField(choices=[(10, '\u5546\u573a\u8ba2\u5355'), (20, '\u4f4f\u5bbf\u8ba2\u5355')], verbose_name='\u8ba2\u5355\u7c7b\u578b')),
                ('order_id', models.CharField(blank=True, default='', max_length=30, verbose_name='\u8ba2\u5355\u53f7')),
                ('order_status', models.IntegerField(blank=True, choices=[(10, '\u672a\u652f\u4ed8'), (15, '\u5f85\u53d1\u8d27'), (20, '\u5f85\u6536\u8d27'), (35, '\u5df2\u5b8c\u6210\u5f85\u8bc4\u4ef7'), (45, '\u5df2\u53d6\u6d88'), (40, '\u8bc4\u4ef7\u5b8c\u6210'), (50, '\u7b49\u5f85\u9000\u6b3e'), (55, '\u9000\u6b3e\u4e2d'), (60, '\u9000\u6b3e\u5b8c\u6210'), (65, '\u5df2\u8fc7\u671f')], default=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('pay_type', models.IntegerField(choices=[(10, '\u79ef\u5206'), (20, '\u4f59\u989d'), (30, '\u5fae\u4fe1\u652f\u4ed8')], default=30, help_text='\u9ed8\u8ba4\u5fae\u4fe1\u652f\u4ed8', verbose_name='\u652f\u4ed8\u65b9\u5f0f')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('num', models.PositiveIntegerField(default=0, help_text='\u5546\u54c1\u603b\u6570\u6216\u8005\u623f\u95f4\u603b\u6570', verbose_name='\u603b\u6570')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0, help_text='\u9700\u8981\u652f\u4ed8\u7684\u91d1\u989d', max_digits=10, verbose_name='\u8ba2\u5355\u4ef7\u683c')),
                ('integral', models.PositiveIntegerField(default=0, help_text='\u53ea\u6709\u5f53\u652f\u4ed8\u65b9\u5f0f\u4e3a\u79ef\u5206\u65f6\u624d\u4f1a\u6709\u8fd9\u4e2a\u5b57\u6bb5', verbose_name='\u79ef\u5206\u603b\u989d')),
                ('operator_time', models.DateTimeField(blank=True, null=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('refund_reason', models.CharField(blank=True, default='', help_text='\u9000\u6b3e\u65f6,\u5fc5\u987b\u586b\u5199', max_length=200, verbose_name='\u9000\u6b3e\u539f\u56e0')),
                ('user_remark', models.TextField(blank=True, default='', verbose_name='\u7528\u6237\u5907\u6ce8')),
                ('operator_remark', models.CharField(default='', max_length=200, verbose_name='\u64cd\u4f5c\u4eba\u5458\u5907\u6ce8')),
                ('belong_hotel', models.ForeignKey(blank=True, help_text='\u53ea\u6709\u5f53\u8ba2\u5355\u7c7b\u578b\u4e3a\u4f4f\u5bbf\u65f6\u624d\u4f1a\u6709\u6b64\u5b57\u6bb5', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Hotel')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Consumer', verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355',
                'verbose_name_plural': '\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='OrderPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_order_id', models.CharField(blank=True, default=0, max_length=32, null=True, verbose_name='\u5fae\u4fe1\u652f\u4ed8\u8ba2\u5355\u53f7')),
                ('free_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u514d\u8d39\u91d1\u989d')),
                ('integral', models.PositiveIntegerField(default=0, verbose_name='\u652f\u4ed8\u79ef\u5206')),
                ('money', models.DecimalField(decimal_places=2, default=0, help_text='\u975e\u514d\u8d39\u91d1\u989d,\u5fae\u4fe1\u652f\u4ed8\u4e3a\u5b9e\u9645\u91d1\u989d, \u4f59\u989d\u652f\u4ed8\u4e3a\u4ece\u5145\u503c\u91d1\u989d\u6263\u53bb\u90e8\u5206', max_digits=10, verbose_name='\u91d1\u989d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pay', to='main.Order', verbose_name='\u8ba2\u5355\u652f\u4ed8\u4fe1\u606f')),
            ],
            options={
                'verbose_name': '\u652f\u4ed8\u4fe1\u606f',
                'verbose_name_plural': '\u652f\u4ed8\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='OrderRefunded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_order_id', models.CharField(default='', max_length=30, verbose_name='\u9000\u6b3e\u8ba2\u5355\u53f7')),
                ('refunded_money', models.DecimalField(decimal_places=2, default=0, help_text='\u5fae\u4fe1\u652f\u4ed8\u65f6,\u6b64\u91d1\u989d\u4e3a\u7528\u6237\u5fae\u4fe1\u652f\u4ed8\u91d1\u989d,\u4f59\u989d\u652f\u4ed8\u65f6\u4e3a\u5145\u503c\u91d1\u989d', max_digits=10, verbose_name='\u9000\u6b3e\u91d1\u989d')),
                ('refunded_free_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u9000\u6b3e\u8d60\u9001\u91d1\u989d')),
                ('refunded_integral', models.PositiveIntegerField(default=0, verbose_name='\u9000\u6b3e\u79ef\u5206')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_refunded', to='main.Order', verbose_name='\u5173\u8054\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u9000\u6b3e\u4fe1\u606f',
                'verbose_name_plural': '\u9000\u6b3e\u4fe1\u606f',
            },
        ),
        migrations.RemoveField(
            model_name='hotelorder',
            name='belong_hotel',
        ),
        migrations.RemoveField(
            model_name='hotelorder',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='hotelorder',
            name='operator_name',
        ),
        migrations.RemoveField(
            model_name='hotelorderroominfo',
            name='belong_order',
        ),
        migrations.RemoveField(
            model_name='hotelorderroominfo',
            name='check_in_room',
        ),
        migrations.RemoveField(
            model_name='marketorder',
            name='consumer',
        ),
        migrations.AlterModelOptions(
            name='hotelorderdetail',
            options={'verbose_name': '\u4f4f\u5bbf\u8ba2\u5355\u8be6\u60c5', 'verbose_name_plural': '\u4f4f\u5bbf\u8ba2\u5355\u8be6\u60c5'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'permissions': [('banner', '\u6a2a\u5e45\u9875'), ('hotel', '\u5bbe\u9986\u4e2d\u5fc3'), ('consumer', '\u5ba2\u6237\u4e2d\u5fc3'), ('role', '\u6743\u9650\u4e2d\u5fc3'), ('distribution', '\u5206\u9500\u4e2d\u5fc3'), ('integral', '\u79ef\u5206\u4e2d\u5fc3'), ('market', '\u5546\u57ce\u4e2d\u5fc3'), ('market_order', '\u5546\u57ce\u8ba2\u5355\u4e2d\u5fc3'), ('tags', '\u6807\u7b7e\u4e2d\u5fc3'), ('staff', '\u804c\u5458\u4e2d\u5fc3'), ('hotel_order', '\u4f4f\u5bbf\u8ba2\u5355')], 'verbose_name': '\u804c\u5458\u4fe1\u606f', 'verbose_name_plural': '\u804c\u5458\u4fe1\u606f'},
        ),
        migrations.RemoveField(
            model_name='hotelorderdetail',
            name='belong_order',
        ),
        migrations.AddField(
            model_name='hotelorderdetail',
            name='contact_name',
            field=models.CharField(default='', max_length=50, verbose_name='\u8054\u7cfb\u4eba'),
        ),
        migrations.AddField(
            model_name='hotelorderdetail',
            name='contact_phone',
            field=models.CharField(default='', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='hotelorderdetail',
            name='reserve_check_in_time',
            field=models.DateTimeField(help_text='\u7528\u6237\u9884\u5b9a\u65f6\u95f4\uff0c12\u70b9\u4ee5\u540e', null=True, verbose_name='\u9884\u5b9a\u5165\u4f4f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='hotelorderdetail',
            name='reserve_check_out_time',
            field=models.DateTimeField(help_text='\u7528\u6237\u9884\u5b9a\u65f6\u95f4', null=True, verbose_name='\u9884\u5b9a\u9000\u623f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='marketorderdetail',
            name='consignee_address',
            field=models.CharField(default='', max_length=200, verbose_name='\u6536\u8d27\u4eba\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='marketorderdetail',
            name='consignee_name',
            field=models.CharField(default='', max_length=50, verbose_name='\u6536\u8d27\u4eba\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='marketorderdetail',
            name='consignee_phone',
            field=models.CharField(default='', max_length=15, verbose_name='\u6536\u8d27\u4eba\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='hotelordercomment',
            name='belong_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='\u5173\u8054\u8ba2\u5355'),
        ),
        migrations.AlterField(
            model_name='marketorderdetail',
            name='market_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_order_detail', to='main.Order', verbose_name='\u5546\u573a\u8ba2\u5355'),
        ),
        migrations.DeleteModel(
            name='HotelOrder',
        ),
        migrations.DeleteModel(
            name='HotelOrderRoomInfo',
        ),
        migrations.DeleteModel(
            name='MarketOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile', verbose_name='\u64cd\u4f5c\u4eba\u5458'),
        ),
        migrations.AddField(
            model_name='hotelorderdetail',
            name='hotel_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_order_detail', to='main.Order', verbose_name='\u6240\u5c5e\u8ba2\u5355'),
        ),
    ]
