# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20181012_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorderdetail',
            name='consignee_address',
            field=models.CharField(default='', max_length=200, verbose_name='\u6536\u8d27\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='\u8ba2\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(10, '\u672a\u652f\u4ed8'), (15, '\u5f85\u53d1\u8d27'), (20, '\u5f85\u6536\u8d27'), (35, '\u5df2\u5b8c\u6210\u5f85\u8bc4\u4ef7'), (45, '\u5df2\u53d6\u6d88'), (40, '\u8bc4\u4ef7\u5b8c\u6210'), (50, '\u7b49\u5f85\u9000\u6b3e'), (55, '\u9000\u6b3e\u4e2d'), (60, '\u9000\u6b3e\u5b8c\u6210'), (65, '\u5df2\u8fc7\u671f'), (70, '\u5df2\u5220\u9664')], db_index=True, default=10, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[(10, '\u5546\u573a\u8ba2\u5355'), (20, '\u4f4f\u5bbf\u8ba2\u5355')], db_index=True, verbose_name='\u8ba2\u5355\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.IntegerField(choices=[(10, '\u79ef\u5206'), (20, '\u4f59\u989d'), (30, '\u5fae\u4fe1\u652f\u4ed8')], db_index=True, default=30, help_text='\u9ed8\u8ba4\u5fae\u4fe1\u652f\u4ed8', verbose_name='\u652f\u4ed8\u65b9\u5f0f'),
        ),
    ]
