# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20181012_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumervipinfo',
            name='consumer',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(10, '\u672a\u652f\u4ed8'), (15, '\u5f85\u53d1\u8d27'), (20, '\u5f85\u6536\u8d27'), (35, '\u5f85\u8bc4\u4ef7'), (45, '\u5df2\u53d6\u6d88'), (40, '\u5df2\u8bc4\u4ef7'), (50, '\u7b49\u5f85\u9000\u6b3e'), (55, '\u9000\u6b3e\u4e2d'), (60, '\u9000\u6b3e\u5b8c\u6210'), (65, '\u5df2\u8fc7\u671f'), (70, '\u5df2\u5220\u9664')], db_index=True, default=10, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='vipmember',
            name='vip_no',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='\u4f1a\u5458\u5361\u53f7'),
        ),
        migrations.DeleteModel(
            name='ConsumerVipInfo',
        ),
    ]
