# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-12 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20181012_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipsettings',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StaffProfile'),
        ),
    ]
