# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-12 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_vipsettings_operator_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='is_vip',
        ),
    ]
