# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-13 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20181012_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargesettings',
            name='free_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u8d60\u9001\u4f59\u989d'),
        ),
        migrations.AlterField(
            model_name='rechargesettings',
            name='recharge_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5145\u503c\u91d1\u989d'),
        ),
    ]
