# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20181013_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='main.HotelOrderComment'),
        ),
        migrations.AlterField(
            model_name='hotelordercomment',
            name='comment_level',
            field=models.IntegerField(choices=[(10, '\u4e00\u5206'), (20, '\u4e24\u5206'), (30, '\u4e09\u5206'), (40, '\u56db\u5206'), (50, '\u4e94\u5206')], default=50, verbose_name='\u8bc4\u8bba\u7b49\u7ea7'),
        ),
    ]
