# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-13 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20181013_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerbalance',
            name='balance_type',
            field=models.IntegerField(choices=[(10, '\u589e\u52a0'), (20, '\u6d88\u8d39')], default=10, verbose_name='\u4f59\u989d\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='rechargeinfo',
            name='free_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u8d60\u9001\u91d1\u989d'),
        ),
        migrations.AlterField(
            model_name='rechargeinfo',
            name='recharge_money',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5145\u503c\u91d1\u989d'),
        ),
    ]
