# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-14 19:16
from __future__ import unicode_literals

from django.db import migrations
import main.modelfields.JsonFields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_orderrefunded_refunded_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstyles',
            name='tags',
            field=main.modelfields.JsonFields.JSONField(default=[], verbose_name='\u6807\u7b7e'),
        ),
    ]
