# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-14 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20181014_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketordercontact',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_order_contact', to='main.Order'),
        ),
    ]
