# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20181014_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelordercomment',
            name='is_reply',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u56de\u590d'),
        ),
    ]
