# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-14 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_hotelordercomment_is_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u5546\u54c1\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_integral',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u79ef\u5206\u5151\u6362'),
        ),
    ]
