# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-14 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20181014_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpay',
            name='integral',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='\u652f\u4ed8\u79ef\u5206'),
        ),
    ]
