# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-14 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20181014_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorderdetail',
            name='integral',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='\u5151\u6362\u79ef\u5206\u5355\u4ef7'),
        ),
        migrations.AlterField(
            model_name='order',
            name='integral',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='\u53ea\u6709\u5f53\u652f\u4ed8\u65b9\u5f0f\u4e3a\u79ef\u5206\u65f6\u624d\u4f1a\u6709\u8fd9\u4e2a\u5b57\u6bb5', null=True, verbose_name='\u79ef\u5206\u603b\u989d'),
        ),
    ]
