# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-16 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20181014_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.PositiveIntegerField(default=0, verbose_name='\u5546\u54c1\u6570\u91cf')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Consumer')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Goods', verbose_name='\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(upload_to=b''),
        ),
    ]
