# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-16 14:31
from __future__ import unicode_literals

from django.db import migrations
import main.modelfields.CompressionImageField


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_auto_20181016_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=main.modelfields.CompressionImageField.CompressionImageField(upload_to=b''),
        ),
    ]
