# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-17 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_auto_20181016_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Goods', verbose_name='\u5546\u54c1'),
        ),
    ]
