# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20181017_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipsettings',
            name='vip_weight',
            field=models.IntegerField(default=0, help_text='\u5f53\u524d\u7528\u6237\u7b49\u7ea7', verbose_name='\u4f1a\u5458\u6743\u91cd'),
        ),
    ]
