# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-17 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_vipsettings_vip_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipsettings',
            name='vip_weight',
            field=models.IntegerField(default=0, help_text='\u5f53\u524d\u7528\u6237\u6743\u91cd,\u503c\u8d8a\u5927,\u4f18\u60e0\u6298\u6263\u66f4\u5927', verbose_name='\u4f1a\u5458\u6743\u91cd'),
        ),
    ]
