# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-17 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20181017_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrderExpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_id', models.CharField(max_length=100, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('express_name', models.CharField(max_length=100, verbose_name='\u5feb\u9012\u540d\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_express', to='main.Order', verbose_name='\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u5feb\u9012\u4fe1\u606f',
                'verbose_name_plural': '\u8ba2\u5355\u5feb\u9012\u4fe1\u606f',
            },
        ),
    ]
