# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_auto_20181017_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='\u63d0\u9192\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_active', models.BooleanField(default=True, help_text='\u662f\u5426\u6709\u6548,\u9ed8\u8ba4\u4e3a\u6709\u6548', verbose_name='\u662f\u5426\u6709\u6548')),
                ('operator_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StaffProfile', verbose_name='\u521b\u5efa\u4eba')),
            ],
            options={
                'verbose_name': '\u7ad9\u5185\u63d0\u9192',
                'verbose_name_plural': '\u7ad9\u5185\u63d0\u9192',
            },
        ),
    ]
