# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-20 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefunded',
            name='refunded_message',
            field=models.CharField(default='', max_length=100, verbose_name='\u9000\u6b3e\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='orderrefunded',
            name='refunded_status',
            field=models.IntegerField(default=50, help_text='\u9000\u6b3e\u72b6\u6001\u3002\u5fae\u4fe1\u53ef\u80fd\u4f1a\u9000\u6b3e\u5931\u8d25', verbose_name='\u9000\u6b3e\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operator_remark',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='\u64cd\u4f5c\u4eba\u5458\u5907\u6ce8'),
        ),
    ]
