# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-22 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_auto_20181021_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketorderdetail',
            old_name='integral',
            new_name='goods_integral',
        ),
        migrations.RenameField(
            model_name='marketorderdetail',
            old_name='sale_price',
            new_name='goods_price',
        ),
    ]
