# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20181022_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiXinPayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_order_id', models.CharField(blank=True, default='', help_text='\u968f\u673a\u751f\u6210', max_length=30, verbose_name='\u4f20\u9012\u7ed9\u8ba2\u5355\u53f7')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('call_back_result', models.CharField(blank=True, default='', max_length=20, verbose_name='\u56de\u8c03\u7ed3\u679c')),
                ('call_back_result_code', models.CharField(blank=True, default='', max_length=20, verbose_name='\u56de\u8c03\u4e1a\u52a1\u7ed3\u679c')),
                ('call_return_msg', models.CharField(blank=True, default='', max_length=100, verbose_name='\u56de\u8c03\u63cf\u8ff0')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Order')),
            ],
            options={
                'verbose_name': '\u5fae\u4fe1\u652f\u4ed8\u4fe1\u606f',
                'verbose_name_plural': '\u5fae\u4fe1\u652f\u4ed8\u4fe1\u606f',
            },
        ),
    ]
