# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-24 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.modelfields.JsonFields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_weixinpayinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRefundedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_express_id', models.CharField(max_length=100, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('user_express', models.CharField(max_length=100, verbose_name='\u5feb\u9012')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('images', main.modelfields.JsonFields.JSONField(default=[], verbose_name='\u56fe\u7247')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_refunded_info', to='main.Order', verbose_name='\u6240\u5c5e\u8ba2\u5355')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u9000\u8d27\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u9000\u8d27\u4fe1\u606f',
            },
        ),
    ]
