# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-25 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_userrefundedinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRefundedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_address', models.CharField(max_length=200, verbose_name='\u9000\u6b3e\u6536\u8d27\u5730\u5740')),
                ('refunded_name', models.CharField(max_length=200, verbose_name='\u9000\u6b3e\u6536\u8d27\u4eba')),
                ('refunded_phone', models.CharField(max_length=30, verbose_name='\u9000\u6b3e\u8054\u7cfb\u7535\u8bdd')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u90ae\u5bc4\u4fe1\u606f',
                'verbose_name_plural': '\u90ae\u5bc4\u4fe1\u606f',
            },
        ),
        migrations.RemoveField(
            model_name='userrefundedinfo',
            name='images',
        ),
        migrations.AddField(
            model_name='order',
            name='fail_reason',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u9000\u6b3e\u5931\u8d25\u539f\u56e0'),
        ),
        migrations.AddField(
            model_name='userrefundedinfo',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(10, '\u672a\u652f\u4ed8'), (15, '\u5f85\u53d1\u8d27'), (20, '\u5f85\u6536\u8d27'), (25, '\u5f85\u5165\u4f4f'), (30, '\u5165\u4f4f\u4e2d'), (35, '\u5f85\u8bc4\u4ef7'), (45, '\u5df2\u53d6\u6d88'), (40, '\u5df2\u8bc4\u4ef7'), (46, '\u7533\u8bf7\u9000\u6b3e'), (48, '\u586b\u5199\u9000\u8d27\u4fe1\u606f'), (50, '\u7b49\u5f85\u9000\u6b3e'), (55, '\u9000\u6b3e\u4e2d'), (60, '\u9000\u6b3e\u5b8c\u6210'), (61, '\u9000\u6b3e\u5931\u8d25'), (65, '\u5df2\u8fc7\u671f'), (70, '\u5df2\u5220\u9664')], db_index=True, default=10, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='adminrefundedinfo',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_refunded_info', to='main.Order', verbose_name='\u9000\u6b3e\u5730\u5740'),
        ),
    ]
