# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-30 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20181025_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrefunded',
            name='refunded_status',
            field=models.IntegerField(choices=[(10, '\u9000\u6b3e\u4e2d'), (20, '\u6210\u529f'), (30, '\u5931\u8d25'), (40, '\u91cd\u8bd5'), (50, '\u672a\u77e5')], default=50, help_text='\u9000\u6b3e\u72b6\u6001\u3002\u5fae\u4fe1\u53ef\u80fd\u4f1a\u9000\u6b3e\u5931\u8d25', verbose_name='\u9000\u6b3e\u72b6\u6001'),
        ),
    ]
