# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-30 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_auto_20181030_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
