# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-01 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20181101_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='avatar_url',
            field=models.CharField(default='', max_length=100, verbose_name='\u5934\u50cf\u94fe\u63a5'),
        ),
    ]
