# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_consumer_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelordercomment',
            name='comment_show',
            field=models.IntegerField(choices=[(10, '\u8bc4\u8bba\u4eba\u53ef\u89c1'), (20, '\u5ba1\u6838\u901a\u8fc7')], default=10, help_text='\u9ed8\u8ba4\u53ea\u80fd\u591f\u8bc4\u8bba\u4eba\u53ef\u89c1', verbose_name='\u8bc4\u8bba\u53ef\u89c1'),
        ),
    ]
