# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-02 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_auto_20181102_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(10, '\u672a\u652f\u4ed8'), (15, '\u5f85\u53d1\u8d27'), (20, '\u5f85\u6536\u8d27'), (25, '\u5f85\u5165\u4f4f'), (30, '\u5165\u4f4f\u4e2d'), (35, '\u5f85\u8bc4\u4ef7'), (45, '\u5df2\u53d6\u6d88'), (40, '\u5df2\u8bc4\u4ef7'), (46, '\u7533\u8bf7\u9000\u6b3e'), (48, '\u586b\u5199\u9000\u8d27\u4fe1\u606f'), (50, '\u7b49\u5f85\u9000\u6b3e'), (55, '\u9000\u6b3e\u4e2d'), (60, '\u9000\u6b3e\u5b8c\u6210'), (61, '\u9000\u6b3e\u62d2\u7edd'), (65, '\u5df2\u8fc7\u671f'), (70, '\u5df2\u5220\u9664')], db_index=True, default=10, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
