# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-07 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_auto_20181106_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionWXInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_payment_no', models.CharField(blank=True, default='', help_text='\u5fae\u4fe1\u5185\u90e8\u8ba2\u5355\u53f7', max_length=100, verbose_name='\u5fae\u4fe1\u4ed8\u6b3e\u8ba2\u5355\u53f7')),
                ('distribution_order_id', models.CharField(blank=True, default='', help_text='\u6210\u529f\u63d0\u53d6\u65f6\u7684\u8ba2\u5355\u53f7', max_length=40, verbose_name='\u63d0\u53d6\u8f6c\u8d26\u8ba2\u5355\u53f7')),
                ('wx_result_code', models.CharField(blank=True, default='', max_length=20, verbose_name='\u5fae\u4fe1\u4e1a\u52a1\u7ed3\u679c')),
                ('err_code', models.CharField(blank=True, default='', max_length=30, verbose_name='\u5fae\u4fe1\u9519\u8bef\u4ee3\u7801')),
                ('err_code_des', models.CharField(blank=True, default='', max_length=100, verbose_name='\u5fae\u4fe1\u9519\u8bef\u63cf\u8ff0')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5fae\u4fe1\u5230\u8d26\u65f6\u95f4')),
                ('distribution_pick', models.ForeignKey(help_text='\u4e00\u4e2a\u7533\u8bf7\u53ef\u80fd\u6709\u591a\u4e2a\u8f6c\u8d26', on_delete=django.db.models.deletion.CASCADE, to='main.DistributionBonusPick')),
            ],
        ),
    ]
