# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_distributionwxinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='\u610f\u89c1\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Consumer')),
            ],
            options={
                'verbose_name': '\u610f\u89c1',
                'verbose_name_plural': '\u610f\u89c1',
            },
        ),
    ]
