# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_opinions'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinions',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
    ]
