# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-15 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_opinions_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_make',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u751f\u6210\u79ef\u5206'),
        ),
    ]
