# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-18 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_order_is_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrefunded',
            name='refunded_order_id',
            field=models.CharField(default='', max_length=35, verbose_name='\u9000\u6b3e\u8ba2\u5355\u53f7'),
        ),
    ]
