# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-19 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_auto_20181118_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionbonuspick',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='distributionbonuspick',
            name='transfer_account',
        ),
        migrations.RemoveField(
            model_name='distributionbonuspick',
            name='transfer_type',
        ),
    ]
